#! /bin/bash
#
#  This installer is mostly provided for testing purposes
#  If you end liking the sofware, ask someone how to package it
#
#  Use it within the application "Terminal"
#
#  First change to its folder by typing:
#  cd "folderFullPath"
#
#  Second make it executable with:
#  chmod ug+x installer
#
#  Then use it with:
#  sudo ./installer OPTION
#  where OPTION is either "-install" or "-remove"


mainFuntion () {
	manageFile "exeCute" "/usr/bin/exeCute"
	manageFile "exeCute.desktop" "/usr/share/applications/exeCute.desktop"
	manageFile "exeCute.svg" "/usr/share/icons/hicolor/scalable/apps/exeCute.svg"
	manageFile "exeCute.1.gz" "/usr/share/man/man1/exeCute.1.gz"
}


changeToProgramDir () {
	cd "$( dirname "${BASH_SOURCE[0]}" )"
	cd ./program
}


manageFile () {
	origin="${1}"
	destiny="${2}"

	if [ "${operation}" == "-install" ]; then
		silently "${operation}" "install -D \"${origin}\" \"${root}${destiny}\""
	elif [ "${operation}" == "-remove" ]; then
		silently "${operation}" "rm \"${root}${destiny}\""
	else
		echo "Unkown operation: ${operation}" >&2
		echo "It should either be \"-install\" or \"-remove\""
		exit 1
	fi
}


silently () {
	function="${1}"
	command="${2}"
	error=$(eval "${command}" 2>&1 >"/dev/null")

	if [ ${?} -ne 0 ]; then
		echo "${function}: ${error}" >&2
		exit 1
	fi
}


operation="${1}"
root="${2}"
changeToProgramDir
mainFuntion
