.TH exeCute "1"

.SH NAME
exeCute - opens exe and bat files as if they were native Linux applications


.SH LAUNCHING

.TP
.SS ON THE FILE MANAGER
Right click on the intended file, and select open with exeCute.

.TP
.SS ON THE TERMINAL
exeCute [filePath]


.SH WINDOWS DISCS

- If you open any disc image with vDisc, any Windows program will recognize it as an optical disc inserted on drive D.


.SH MS-DOS DISCS

- If the launched program folder contains any disc images, they will be made available on drive D.

- If there are multiple images, you can change among them with: Control + F4.

- Compatible disk images are '.iso', '.cue' and '.gog'.

- If there is no disc image, the launched program folder will be made also available on drive D.


.SH VIRTUAL DESKTOP

If a Windows application doesn't show properly, you can try launching it on a virtual desktop.

For that, in the application directory, create a file named 'desktop.conf'.

If you want the desktop to have a particular resolution, type it inside that file.
