.TH exeCute "1"

.SH NAME
exeCute - opens exe and bat files as if they were native Linux applications


.SH LAUNCHING

.TP
.SS ON THE FILE MANAGER
Right click on the intended file, and select open with exeCute.

.TP
.SS ON THE TERMINAL
exeCute [filePath]


.SH USING A VIRTUAL DESKTOP

If a Windows application doesn't show properly, you can try launching it on a virtual desktop.

For that, in the application directory, create a file named 'desktop.conf'.

If you want the desktop to have a particular resolution, type it inside that file.


.SH AUTOMOUNTING MS-DOS DISK IMAGES

- exeCute will automount any disk images under the launched program folder, on drive 'D'.

- You can change among multiple disk images with: Control + F4.

- Compatible disk images are '.iso', '.cue' and '.gog'.

- If there is no disk image, the launched program folder will be mounted also on drive 'D'.
